### ISSUE TITLE
El requerimiento era prender todos los leds en una operación

### ISSUE THREAD

**Issue by evolentini** [monzonlucasfabricio/Testing_TP3#2]
De nuevo este código tiene severos problemas: pasar un arreglo sin especificar el tamaño genera errores de acceso a memoria. Ademas esta implementación ocupa 16 bytes de la pila cuando la implementación normal no requiere ningún parámetro.

https://github.com/monzonlucasfabricio/Testing_TP3/blob/f26a2ae258ddd929e6f17396c4e9123d9517cc74/test/test_leds.c#L87-L91

**Comment by monzonlucasfabricio** [comment]
Hola Esteban, el problema entonces viene en la creación de un array de 16
bytes dentro de la función de test? ¿Que conviene pasarle a la función si
no es un array de los leds que quiero prender?.

Saludos,
Lucas.
